### ISSUE TITLE
Support Kotlin

### ISSUE THREAD

**Issue by dvdciri** [dvdciri/daggraph#16]
At the moment the tool only supports java applications, we need to extend the support for Kotlin applications as well.

Things that needs to be done:
- Update the extension when looking for the files
- Update all the regex and make sure they all support java and kotlin at the same time

**Comment by dvdciri** [comment]
@ravidsrk @v3n3 we can track the progress of that from here

**Comment by v3n3** [comment]
👍

**Comment by dvdciri** [comment]
Support for kotlin has been shipped with the new release 0.2.4. Closing this
