### ISSUE TITLE
Export the raw graph

### ISSUE THREAD

**Issue by dvdciri** [dvdciri/daggraph#23]
### Description
It would be good to be able to export the raw graph as json

**Comment by Mishkun** [comment]
Maybe not the json but as DOT language file? Then it can be opened with many editors, such as GraphViz or Gephi.

**Comment by dvdciri** [comment]
@Mishkun Do you have any ideas on how it can be achieved? 

This is an interesting cli that might help with that https://github.com/jsongraph/jgf-dot
