### ISSUE TITLE
Doesn't support fully qualified @Component reference

### ISSUE THREAD

**Issue by orrc** [dvdciri/daggraph#25]
### Description
Running `daggraph` on a project whose component has an annotation `@dagger.Component` (because the interface itself is also called `Component`, for example), does not work.

Changing the Java source temporarily to `@Component` works as expected.

### Steps to reproduce
1. Create a Dagger1 project
2. Create a file: `@dagger.Component public interface Component {}`
3. Run `daggraph`
4. See "Couldn't find any components, are you sure this project is using Dagger?"

### Expected behaviour
The component should be detected.

**Comment by dvdciri** [comment]
Good catch, will need to improve the search regex for @Component adding more flexibility

**Comment by dvdciri** [comment]
Fix available in v0.2.5
