### ISSUE TITLE
UnsupportedOperationException: The BROWSE action is not supported

### ISSUE THREAD

**Issue by regisd** [dvdciri/daggraph#32]
### Description
Generation of the graph fails

### Steps to reproduce
Generate depenency injection graph

### Expected behaviour
Graph generated

### Screenshot
https://imgur.com/1fq2TkY

**Comment by regisd** [comment]
From idea.log


> 2018-01-26 12:48:38,323 [2852165]  ERROR - pplication.impl.LaterInvocator - The BROWSE action is not supported on the current platform! 
> java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
> 	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
> 	at java.awt.Desktop.browse(Desktop.java:381)
> 	at actions.GenerateDependencyInjectionGraph$1.onSuccess(GenerateDependencyInjectionGraph.java:127)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:470)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.lambda$run$0(ProgressManagerImpl.java:161)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by regisd** [comment]
Environment:

- Debian rodete
- Chrome 63.0.3239.132 (Official Build) (64-bit)
- Android Studio 3.0.1
- openjdk version "1.8.0_112"

**Comment by dvdciri** [comment]
Are you trying to use the tool via android studio plugin? It hadn't been designed to work like that, please follow the read me file for usages.
