### ISSUE TITLE
Support other DI framework

### ISSUE THREAD

**Issue by afaucogney** [dvdciri/daggraph#33]
### Description

I would like to support another DI framework that also implement the JSR330 : Tootphpick

### Expected behaviour

As the framework use mainly @Inject annotation, eg : the binding is implemented inside module is done by code. I would like to just make a graph from @Inject. How this is possible ? Where to start ?

**Comment by dvdciri** [comment]
Thanks for the issue, there are currently no plans to support other DI frameworks in the future. If you want to give it a try you can still fork the repository and use it as a base.
