### ISSUE TITLE
ActivityBuilder Modules are not generated in the graph

### ISSUE THREAD

**Issue by kazaky** [dvdciri/daggraph#37]
### Description
ActivityBuilder Modules are not generated in the graph

### Example of ActivityBuilderModule
@Module
public abstract class ActivityBuilder {
    @ContributesAndroidInjector(modules = SplashActivityModule.class)
    abstract SplashActivity bindSplashActivity();
}

**Comment by dvdciri** [comment]
Yes correct, that is a missing feature. Will add that in the "what's supported" section. Thanks

**Comment by dvdciri** [comment]
Closing this as update the README file with the missing feature. Thanks again for reporting it.
