### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] After upgrade to 0.3.0

### ISSUE THREAD

**Issue by tharoldD** [dvdciri/daggraph#39]
### Description
After upgrade to version 0.3.0, running the command produces error...

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string`

See full trace in screenshot.

### Steps to reproduce
run

`npm -g i daggraph`
`cd <to project folder>`
`daggraph`

### Expected behaviour
Default browser should open tab showing dependency graph

### Screenshot
<img width="525" alt="screen shot 2018-04-01 at 12 09 51 copy" src="https://user-images.githubusercontent.com/5029799/38171765-bccca324-35a8-11e8-945b-b62e62ca6147.png">

**Comment by dvdciri** [comment]
Thanks for reporting this. It's definitely a bug and i've opened a PR to fix this. #41

**Comment by dvdciri** [comment]
Fix available in release 0.3.1

**Comment by tharoldD** [comment]
Fix working, thanks
