### ISSUE TITLE
Possibility of switching to bytecode/apk analyzing instead of source?

### ISSUE THREAD

**Issue by Dkhusainov** [dvdciri/daggraph#46]
Hello.

First of all, this is a great tool and I really like the concept, but it laks flexibility. 

Right now it only works on source code. Which means It cannot detect Modules/Components from other libraries(because accessing their source code is very difficult).  Or Providers/injectors generated in aar module. Also you have implement different rules for Kotlin.

Would you consider switching to analyzing apk directly? Here's the tool that does something simular, but it build graph of all the classes. https://github.com/alexzaitsev/apk-dependency-graph/issues

**Comment by dvdciri** [comment]
Unfortunately there are no plans to support analization of the apk as this tool was intended to be use during development for refactoring or integration of the dependencies.
