### ISSUE TITLE
'This is not a gradle folder' on a gradle setup with kotlin build files

### ISSUE THREAD

**Issue by jzillmann** [dvdciri/daggraph#55]
### Description
Using the tool on a dagger project setup with gradle but with the new Kotlin build scripts ('build.gradle.kts') fails with the message `This is not a gradle folder`.

### Steps to reproduce
Don't have a public example to share...

### Expected behaviour
Should work for gradle/kotlin as well/

**Comment by jzillmann** [comment]
Question: Why is there a gradle check in the first place ? Are you extracting any information from the gradle setup ?

**Comment by dvdciri** [comment]
It was to check that it's an android application folded, this check could be removed or we could find a better way to check that. Open to suggestions and PRs =)
